### PR TITLE
Eclipse bug 54116

### PR DESCRIPTION
**Pull request by mmariia**
Port fix for eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=54116 until we switch to 4.13 M1 or higher.

### CODE REVIEW

**Comment by ybova** [comment]
Since SVG support is still under development, it's safer to comment out lines 181-201 in ImageDescriptor.java that were added in 49bb1a35f1b1f2d45320b7ae82551de68c70e992

**Comment by eugenekotovhalliburton** [comment]
> Since SVG support is still under development, it's safer to comment out lines 181-201 in ImageDescriptor.java that were added in [49bb1a3](https://github.com/Halliburton-Landmark/eclipse.platform.ui/commit/49bb1a35f1b1f2d45320b7ae82551de68c70e992)

Maria M already commented that part

**Comment by mmariia** [comment]
> Since SVG support is still under development, it's safer to comment out lines 181-201 in ImageDescriptor.java that were added in [49bb1a3](https://github.com/Halliburton-Landmark/eclipse.platform.ui/commit/49bb1a35f1b1f2d45320b7ae82551de68c70e992)

Done

**Comment by ybova** [comment]
Looks good. We will create a separate branch for SVG support.

**Pull request merged**
